FROM eclipse-temurin:25-jdk-alpine-3.23
WORKDIR /app
COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts . 
COPY settings.gradle.kts .

RUN chmod +x ./gradlew 
RUN ./gradlew dependencies

COPY src src 
RUN ./gradlew bootJar 

FROM eclipse-temurin:25-jre-alpine-3.23
WORKDIR /app 
COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]


